gui:
  scrollHeight: 8
  scrollPastBottom: false
  showFileTree: false
  showRandomTip: false
  showBottomLine: true
notARepository: 'skip'
git:
  branchLogCmd: "git lg"
  pagers:
    - colorArg: always
      pager: delta --diff-so-fancy --dark --paging=never
